### ISSUE TITLE
Consider moving react component to superhero-button

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-button-react#2]
Marking `react` an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies)

**Comment by shapkarin** [comment]
I think that `peerDependencies` is enough and it conflicts with the optional

**Comment by shapkarin** [comment]
BTW thanks for the `peerDependencies` at [extend-saga-routines](https://github.com/shapkarin/extend-saga-routines/blob/bc8e52d6f51ef6021338c229248756fbbff6b4dc/package.json#L53-L56) I use tham but forgot to add a react to this one.

**Comment by davidyuk** [comment]
I'm proposing to:
- investigate the difference between `peerDependencies` and `optionalDependencies`
- make this component a part of `@aeternity/superhero-button`

Because I don't think that we need a separate repo for this react component. `peerDependencies`/`optionalDependencies` should handle the lack of React in cases if it is not needed.

related issue: https://github.com/aeternity/superhero-button/issues/11

@mradkov what do you think?

**Comment by mradkov** [comment]
> I'm proposing to:
> 
>     * investigate the difference between `peerDependencies` and `optionalDependencies`
> 
>     * make this component a part of `@aeternity/superhero-button`
> 
> 
> Because I don't think that we need a separate repo for this react component. `peerDependencies`/`optionalDependencies` should handle the lack of React in cases if it is not needed.
> 
> related issue: [aeternity/superhero-button#11](https://github.com/aeternity/superhero-button/issues/11)
> 
> @mradkov what do you think?

Agree. I also think we do not need to maintain separate repo for this.

**Comment by shapkarin** [comment]
> * investigate the difference between `peerDependencies` and `optionalDependencies`

@mradkov @davidyuk my opinion that while develop not install the the `peerDependencies` he can't run the project. So in that case `optionalDependencies` is in conflict with `optionalDependencies`.

**Comment by shapkarin** [comment]
> > * investigate the difference between `peerDependencies` and `optionalDependencies`
> 
> @mradkov @davidyuk my opinion that while develop not install the the `peerDependencies` he can't run the project. So in that case `optionalDependencies` is in conflict with `optionalDependencies`.

and maybe it's good because this project is name `superhero-button-react` and it must to use the react but it request to add the wepback for exmaple and bundle scripts.

**Comment by shapkarin** [comment]
> I'm proposing to:
> 
> * investigate the difference between `peerDependencies` and `optionalDependencies`
> * make this component a part of `@aeternity/superhero-button`
> 
> Because I don't think that we need a separate repo for this react component. `peerDependencies`/`optionalDependencies` should handle the lack of React in cases if it is not needed.
> 
> related issue: [aeternity/superhero-button#11](https://github.com/aeternity/superhero-button/issues/11)
> 
> @mradkov what do you think?

I think that react component is more easy to in React environment, it's more readable and the same with other code and it can create help to create more features in the future like tip directly to the user with input while we someone with help of [aeternity/jitsi-meet](https://github.com/aeternity/jitsi-meet)

**Comment by shapkarin** [comment]
> I'm proposing to:
> 
> * investigate the difference between `peerDependencies` and `optionalDependencies`
> * make this component a part of `@aeternity/superhero-button`
> 
> Because I don't think that we need a separate repo for this react component. `peerDependencies`/`optionalDependencies` should handle the lack of React in cases if it is not needed.
> 
> related issue: [aeternity/superhero-button#11](https://github.com/aeternity/superhero-button/issues/11)
> 
> @mradkov what do you think?

I think that react component is more easy to in React environment, it's more readable and the it more same with other code in the React project and it can help to create more features in the future like tip directly to the user with input while we talk with someone with help of [aeternity/jitsi-meet](https://github.com/aeternity/jitsi-meet)

**Comment by shapkarin** [comment]
> I'm proposing to:
> 
> * investigate the difference between `peerDependencies` and `optionalDependencies`
> * make this component a part of `@aeternity/superhero-button`
> 
> Because I don't think that we need a separate repo for this react component. `peerDependencies`/`optionalDependencies` should handle the lack of React in cases if it is not needed.
> 
> related issue: [aeternity/superhero-button#11](https://github.com/aeternity/superhero-button/issues/11)
> 
> @mradkov what do you think?

I think that react component is more easy to use in React environment, it's more readable and the it more same with other code in any React project and it can help to create more features in the future like tip directly to the user with input. For example while we talk with someone with help of [aeternity/jitsi-meet](https://github.com/aeternity/jitsi-meet)

**Comment by shapkarin** [comment]
> tip directly to the user with input

I mean with an input like we have at `retip` at superhero-ui

**Comment by shapkarin** [comment]
[this usage](https://github.com/aeternity/jitsi-meet/blob/90fa02b4e1533923bed657cb83e6765fae14aeaa/react/features/toolbox/components/web/Toolbox.js#L340-L342) can confuse someone some in React project because all elements that are mounted are in the `render` or returned with functional component. That's also the reason to wrap the button to the component.

**Comment by shapkarin** [comment]
@davidyuk @mradkov I'm sorry if my messages was too much emotional.

**Comment by shapkarin** [comment]
@davidyuk @mradkov I think that it also need the same functionality as button at superhero-ui some user profile section has. Pay directly to the user. Thanks @mradkov to notice that we have such.
<img width="62" alt="Снимок экрана 2020-07-11 в 17 46 55" src="https://user-images.githubusercontent.com/1463086/87226744-86adaf00-c39e-11ea-80eb-e3a204fb1c26.png">

**Comment by shapkarin** [comment]
@mradkov after conversation in direct messages with @davidyuk I realised his thought about that all. So we think to do next:
- move react component to the @aeternity/superhero-button repo
- create new entry point like @aeternity/superhero-button/react ~~and use tree shaking to avoid the useless builders decrease~~
- make React as an optionalDependency
- add some features to the component like we have at superhero-ui profiles pages.

@mradkov can you confirm?

**Comment by davidyuk** [comment]
> add some features to the component like we have at superhero-ui profiles pages

actually, I'm not a fan of this idea, `superhero-button` has a specific use case and we need to ensure that it is useful to add new features

**Comment by shapkarin** [comment]
@davidyuk my point that we have 

> > add some features to the component like we have at superhero-ui profiles pages
> 
> actually, I'm not a fan of this idea, `superhero-button` has a specific use case and we need to ensure that it is useful to add new features

it's useful for the jitsi-meet fork. but at this time it can be done as part of that fork. later I think to move it to some repo and module. maybe `superhero-button`
